#!/bin/bash
# Jenkins-build trigger

BASEDIR=$(dirname $(readlink -f $0))
VENV=venv
ACTIVATE=$VENV/bin/activate
STATUS=false

# Username
machine=$(uname -n)

echo "Notifying Jenkins Server to execute a Build on " $machine
# Logic to check if commit is done or merged to a particular branch / master branch

cd $BASEDIR
# Change directory to parent directory, since current directory is `.git/hooks/`
cd ../..

# Check if venv folder exists, if it does not then create it
if [ ! -d "$VENV" ]; then
  # Control will enter here if $VENV doesn't exist.
  virtualenv -p python3 $VENV
  STATUS=true
fi

# Source virtual environment
source $ACTIVATE

# Install required dependencies if not yet installed
if [ "$STATUS" = true ]; then
    # if status is true, means need to install all the required libraries
    pip install --upgrade pip
    pip install -r requirements.txt
fi

# check current git branch
BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
echo $BRANCH
if [ "$BRANCH" = "master" ]; then
    # if branch is master, then only proceed.
    # Start processing jenkins jobs
    python last_dir_processed.py
else
    echo "Current Branch $BRANCH, Nothing to execute."
fi

# Deactivate virtual environment
deactivate
