#!/bin/bash
# Jenkins-build trigger

BASEDIR=$(dirname $(readlink -f $0))
VENV=venv
ACTIVATE=$VENV/bin/activate
STATUS=false

# Username
machine=$(uname -n)

echo "Notifying Jenkins Server to execute a Build on " $machine
# Logic to check if commit is done or merged to a particular branch / master branch

cd $BASEDIR
cd ../..

# Check if venv folder exists, if it does not then create it
if [ ! -d "$VENV" ]; then
  # Control will enter here if $VENV doesn't exist.
  virtualenv -p python3 $VENV
  STATUS=true
fi

# Source virtual environment
source $ACTIVATE

# Install required dependencies if not yet installed
if [ "$STATUS" = true ]; then
    # if status is true, means need to install all the required libraries
    pip install --upgrade pip
    pip install -r requirements.txt
fi

# Start processing jenkins jobs
python last_dir_processed.py

# Deactivate virtual environment
deactivate
